server:
  port: 9010

spring:
  application:
    name: cusmuliuc
  h2:
    console:
      enabled: true
      path: /h2
  datasource:
    url: jdbc:h2:mem:cusmuliuc;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
    platform: h2
    username: sa
    password: null
    driverClassName: org.h2.Driver
    jpa:
      database-platform: org.hibernate.dialect.H2Dialect
      hibernate:
        ddl-auto: update
        properties:
          hibernate:
            show_sql: true
            use_sql_comments: true
            format_sql: true